# docker
abbr -S --quiet d="docker"
abbr -S --quiet --quieter --force dc="docker compose"
abbr -S --quiet "docker i.l.a"="docker image ls --all"
abbr -S --quiet "docker i.l"="docker image ls"
abbr -S --quiet "docker i.p"="docker image prune"
abbr -S --quiet "docker i.r"="docker image rm"
abbr -S --quiet "docker i"="docker image"
abbr -S --quiet "docker c.l.a"="docker container ls --all"
abbr -S --quiet "docker c.l"="docker container ls"
abbr -S --quiet "docker c.p"="docker container prune"
abbr -S --quiet "docker c.r"="docker container rm"
abbr -S --quiet "docker c"="docker container"
abbr -S --quiet "docker v"="docker volume"
abbr -S --quiet "docker v.l"="docker volume ls"
abbr -S --quiet "docker v.p"="docker volume prune"
abbr -S --quiet "docker v.r"="docker volume rm"
